### ISSUE TITLE
backport for `tools::R_user_dir()`?

### ISSUE THREAD

**Issue by matthewhillary** [MilesMcBain/rmdocs#6]
I'm back on R 3.6 and can't install {rmdocs} since it uses `tools::R_user_dir()`.  Any chance of backporting this function or do I need to bite the bullet and update?

**Comment by MilesMcBain** [comment]
I'm now using the version form `{backports}`, hopefully that works for you @matthewhillary!

**Comment by matthewhillary** [comment]
Perfect, that works thanks!
